version: '3.7'
services:
   nginx:
     container_name: nginx-container
     image: nginx-image:latest
     build:
        context: .
        dockerfile: Dockerfile
     ports:
     - "8082:80"
     - "8083:80"


