services:
   nginx:
     container_name: ${containerName}
     image: ${baseImageName}
     build:
        context: .
        #dockerfile: Dockerfile-commonBuild
        dockerfile: Dockerfile
     ports:
       - ${appPort}:${containerPort}


