services:
   nginx:
     container_name: ${containerName}
     image: ${baseImageName}
     env_file :
       - ${environment}.env
     volumes :
       - /src/environments/environment.ts:/usr/share/nginx/assets/runtime-environment.json
     build:
        context: ../
        #dockerfile: docker/Dockerfile-commonBuild
        dockerfile: docker/Dockerfile
     ports:
       - ${appPort}:${containerPort}