services:
   docker-nginx:
     container_name: ${containerName}
     deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
     environment: #run time arguments
       - env=${environ}
     build:
        args:  #these args are available during build time
           - env=${environ}
        context: ../
        dockerfile: docker/Dockerfile
     ports:
       - ${appPort}:${containerPort}

  #  nginx-prod:
  #     extends:
  #       file: common.yml
  #       service: app
  #     image: ${DOCKER_HUB_CRED_USR}/${toRepositoryName}:${tag}

  #  nginx-uat:
  #     extends:
  #       file: common.yml
  #       service: app
  #     image: ${DOCKER_HUB_CRED_USR}/${toRepositoryName}:${tag}