# If deploying to a remote server, we normally have seperate servers for each environment. 
# thus a single service is enough when deploying to a server.
services:
   docker-nginx:
    container_name: angular-nginx-${environ}-container
    environment: #run time arguments
       - env=${environ}
    build:
        context: ../
        dockerfile: docker/Dockerfile

 
  #docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml build
  #docker compose -f docker/docker-compose.yml -f docker/docker-compose.prod.yml build
  #docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up -d --remove-orphans --no-build
  #docker compose -f docker/docker-compose.yml -f docker/docker-compose.prod.yml up -d --remove-orphans --no-build