services:
   nginx:
     container_name: ${containerName}
     image: ${baseImageName}
     env_file :
       - ${environment}.env # available only at run time
     build:
        args:
           - name=DEV
           - port=8082
        context: ../
        #dockerfile: docker/Dockerfile-commonBuild
        dockerfile: docker/Dockerfile
     ports:
       - ${appPort}:${containerPort}