services:
   nginx:
     container_name: ${containerName}
     image: ${baseImageName}
     env_file :
       - ${environment}.env
    #  command : ["nginx", "-g", "daemon off;"] 
     args:
        - name=${name}
        - port=${port}
     build:
        context: ../
        #dockerfile: docker/Dockerfile-commonBuild
        dockerfile: docker/Dockerfile
     ports:
       - ${appPort}:${containerPort}