services:
   nginx-dev:
      extends:
        file: common.yml
        service: app

   nginx-prod:
      extends:
        file: common.yml
        service: app

   nginx-uat:
      extends:
        file: common.yml
        service: app