services:
   nginx-dev:
      extends:
        file: common.yml
        service: app
      ports:
        - 8082:80

   nginx-prod:
      extends:
        file: common.yml
        service: app
      image: ${DOCKER_HUB_CRED_USR}/${toRepositoryName}:${tag}
      ports:
        - 8083:80

   nginx-uat:
      extends:
        file: common.yml
        service: app
      image: ${DOCKER_HUB_CRED_USR}/${toRepositoryName}:${tag}
      ports:
        - 8084:80


  #docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml build
  #docker compose -f docker/docker-compose.yml -f docker/docker-compose.prod.yml build
  #docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up -d --remove-orphans --no-build
  #docker compose -f docker/docker-compose.yml -f docker/docker-compose.prod.yml up -d --remove-orphans --no-build