services:
   nginx:
     container_name: ${containerName}
     image: ${baseImageName}
     env_file :
       - ${environment}.env
    #  command : ["nginx", "-g", "daemon off;"] 
     build:
        context: ../
        #dockerfile: docker/Dockerfile-commonBuild
        dockerfile: docker/Dockerfile
        args:
           name:${name}
           port:${port}
     ports:
       - ${appPort}:${containerPort}