services:
   nginx:
     container_name: ${containerName}
     image: ${baseImageName}
     env_file :
       - ${environment}.env
     command: envsubst < "$name,$port" > "/src/assets/runtime-environment.ts" && nginx -g 'daemon off;'
     volumes :
       - /src/assets/runtime-environment.ts:/usr/share/nginx/assets/runtime-environment.ts
     build:
        context: ../
        #dockerfile: docker/Dockerfile-commonBuild
        dockerfile: docker/Dockerfile
     ports:
       - ${appPort}:${containerPort}